### ISSUE TITLE
Show error message when there's no Git

### ISSUE THREAD

**Issue by domyen** [chromaui/chromatic-cli#146]
**Why?** 
We get a lot of support issues about different git capabilities in CI environments. This often takes non-trivial back and forth to resolve. In some cases, it's [not obvious](https://app.intercom.com/a/apps/zj7sn9j1/inbox/inbox/all/conversations/27253866149). We should diagnose git issues and proactively recommend a solution _before_ they contact us. That helps users resolve issues faster by themselves.

**From recent memory:**
- Github actions fetch depth
- Jenkins configuration doesn’t expose git
- Docker images without git

With `git rev-list HEAD --count` we may have a heuristic for determining git capabilities of the users CI environment. If the user doesn't have git: 
- Show a CLI error message that tells them what's going on and how to resolve. (existing error messages [here](https://5d67dc0374b2e300209c41e7-axronkchqy.chromatic.com/?path=/story/cli-messages-errors--build-has-changes))
- Link to docs (we'll need to write these)

**Comment by ghengeveld** [comment]
When trying to run Chromatic in a non-git project (or git is otherwise not available), we currently show the following:

<img width="855" alt="Screenshot 2020-11-09 at 15 02 41" src="https://user-images.githubusercontent.com/321738/98550690-b44b2c00-229c-11eb-83d2-b5450834c265.png">

I've added a warning when running from a shallow clone, and updated the rest of the git/CI messages and added stories for them: https://github.com/chromaui/chromatic-cli/pull/207
