### ISSUE TITLE
Chromatic CLI is trying to merge to main branch

### ISSUE THREAD

**Issue by vfonic** [chromaui/chromatic-cli#183]
Hey everyone!

Thanks for building this tool!

I'm just trying to setup Storybook and Chromatic for an existing project of mine, for the first time.
I got Storybook to work. Then I discovered Chromatic and decided to set it up as well.

I published my first build. I continued following the steps and went to "PRs" and "Changeset". There I found this bit of text:
> We'd love to show you visual changes, but we don't have anything to compare to yet. Here's what you need to do:
> * Create a build on storybook
> * Checkout storybook if you haven't already
> `git checkout storybook`
> Don't forget to install or update dependencies after switching branches.
> * Run a patch build for this pull request against master
> `npx chromatic --project-token=oyx4fxquu3q --patch-build=storybook...master`

I was shocked to realize that "run a patch build against master" tried to merge the PR (to master)!
I'm not sure 100% if that's the case. All I see is that it fails (as direct merging is blocked).

The error message I get is:
> Failed to collect Storybook metadata
> Could not find a supported Storybook viewlayer package. Make sure one is installed.

Maybe I misunderstood what "Run a patch build for this pull request against master" means. But to me this seems dangerous. I had some unchecked code and I definitely didn't want that, setting up a testing tool, pretty much deploys new code to my live site (we have automatic deployment set up on master).

My suggestion would be to be more explicit about what is going to happen after running that npm script.

PS What would be a good next step for me to have Chromatic fully working? I guess (eventually) merging the PR and then, after creating another one, we'll be able to see it in action?

**Comment by tmeasday** [comment]
Hi @vfonic,

Don't worry, Chromatic will not merge or push any changes to your branches! You can read about what a patch build is and what the motivation for creating one is here: https://www.chromatic.com/docs/branching-and-baselines#patch-builds

It sounds like we need to make it clearer what the patch build is going to do.

In your case it sounds like the problem is that you didn't have Storybook installed at all on the base build of the PR, which is why Chromatic is tripping up when it tries to run there.

> PS What would be a good next step for me to have Chromatic fully working? I guess (eventually) merging the PR and then, after creating another one, we'll be able to see it in action?

That would probably be the easiest way to see UI review in action. Another option would be to make a branch *off* your `storybook` branch, make some changes in it, then PR it back into the `storybook` branch.

**Comment by vfonic** [comment]
Thanks @tmeasday!

That's good to hear! I was worried what Chromatic was trying to do.

Speaking of the "build issue", I guess one of the quite possible scenarios is that someone sets up Storybook and Chromatic at the same time, just like I did. I'd say this should be accounted for so that, when Chromatic notices that there's no Storybook on main branch, it tells the user that user should first merge to main and then he'll be able to get the passing build/see the diff.
