### ISSUE TITLE
chromatic package messing with some test cases

### ISSUE THREAD

**Issue by carlosberti** [chromaui/chromatic-cli#199]
Hey guys. I hope you doing ok!

I was working on a project this weekend and came across a possible and tricky problem with jest and chromatic.

At first I thought I had made something without notice, and that broke the test. After spent some time looking for the possible problem, I started to think it could have been chromatic, because it was the last thing I did before the tests stopped working.

I deployed my project to vercel and all the tests worked fine as they should. Later, i installed chromatic into the project `yarn add -D chromatic` and after that, some test cases started to fail. I will let you screenshots to show the strange error that is occuring.

So, this image below is my project on [main](https://github.com/carlosberti/financeWizard/tree/main) branch, where chromatic is not installed.

![image](https://user-images.githubusercontent.com/22118601/97098723-344b8200-165f-11eb-95ee-d4a9ef160a7b.png)

As you can see, all tests are green and happy.

And this image is on [test-problem-chromatic](https://github.com/carlosberti/financeWizard/tree/test-problem-chromatic) branch.

![image](https://user-images.githubusercontent.com/22118601/97098768-91dfce80-165f-11eb-964f-f373793d75b3.png)

And here starts the problem.

Here i show you that 4 test cases has failed

![image](https://user-images.githubusercontent.com/22118601/97098774-a58b3500-165f-11eb-82e8-8d199623270e.png)

**Comment by tmeasday** [comment]
Hi @carlosberti -- are you importing Chromatic anywhere in your code? If not, unless something really odd has happened with your `node_modules`, I doubt it could be affecting your tests. Perhaps you should try reverting to before you added Chromatic run the tests again?

**Comment by carlosberti** [comment]
Hey @tmeasday. I'm not importing at all, I just added it to deploy storybook. I invite you to take a look on my [branch ](https://github.com/carlosberti/financeWizard/tree/test-problem-chromatic). Clone it, run `yarn test`, remove chromatic and run again `yarn test`. You will see that is an odd behavior

**Comment by tmeasday** [comment]
Hmm, yes that is pretty odd! I am not sure what is happening there, to be honest I can't really understand how your test works in the first place (I probably just don't understand this testing libraries properly), but it certainly shouldn't change when you install `chromatic`.

I think this issue is we seem to accidentally have a dependency on `jest` (a different one to the version your app using) in the `chromatic` package (rather than a `devDependency`) and it must be doing something weird to your test environment. We'll try and get a new version of our package out without these extraneous dependencies soon!

**Comment by carlosberti** [comment]
Ok @tmeasday, thanks for your support!

**Comment by tmeasday** [comment]
@carlosberti this was cleaned up in 5.3.0 so perhaps you could try upgrading?
