### ISSUE TITLE
Use commit from env-ci

### ISSUE THREAD

**Issue by kylesuss** [chromaui/chromatic-cli#215]
We have a customer that uses `env-ci` & runs builds on PRs only (in addition to master). When that happens in their CI flow, the commit is not right. Rather than having to set both `CHROMATIC_SHA` and `CHROMATIC_BRANCH`, they are suggesting that we use the `commit` from `envCI` whenever we hit this code block:

https://github.com/chromaui/chromatic-cli/blob/ee1607225351856fd4920057e354efc0a5d8f295/bin/git/getCommitAndBranch.js#L79-L80

There is a complication with `env-ci` and setting `CHROMATIC_BRANCH` in the sense that the branch is determined via some conditional logic:

https://github.com/pvdlg/env-ci/blob/73299d7f729971a2725cff8b582367f108cfb5ea/services/vsts.js#L18

and they would rather not replicate that, which is fair. Is this a feasible option for us?

https://app.intercom.com/a/apps/zj7sn9j1/inbox/inbox/all/conversations/27253889238

**Comment by travi** [comment]
from what i've grown to understand about the implementation, it seems like pulling the commit from what `env-ci` is already calculating across various possible ci services should solve this situation well. 

i'm sure you're already aware of how well `env-ci` solves problems like these since you are already using parts of it, but i can reiterate how battle tested it is through our use of it in `semantic-release`

it also seems like this approach could probably simplify the [special cases](https://github.com/chromaui/chromatic-cli/blob/ee1607225351856fd4920057e354efc0a5d8f295/bin/git/getCommitAndBranch.js#L80) that you currently check for with travis-ci and github since `env-ci` already returns the same values. you could likely support more cases than those two, which would cover our need in the context of azure dev ops.

i did not include anything along those lines in my PR since it think the simple change will cover the needs. i could see releasing an update with the simple change and potentially simplifying as a follow up.

**Comment by tmeasday** [comment]
I think it makes sense to lean on envci if it is doing the job already, for sure.
