### ISSUE TITLE
Include external dom created from react portal in snapshot

### ISSUE THREAD

**Issue by marcoburrometo** [chromaui/chromatic-cli#271]
Hello all, i hope this is the right place.
I've made a component to handle floating elements using React portal and position fixed, so the dom is added to body and not inside the element itself.
This "floating" element isn't included in the snapshot itself, but in canvas i see it correctly.
I already tried with delay and different viewports

**Comment by marcoburrometo** [comment]
solved it with a wrapping div with fixed height and width

**Comment by stivaugoin** [comment]
Hey @marcoburrometo I have the same problem and I don't understand how you fixed it. Where do you add the div? Do you have a short example please?

Thanks

**Comment by marcoburrometo** [comment]
> Hey @marcoburrometo I have the same problem and I don't understand how you fixed it. Where do you add the div? Do you have a short example please?
> 
> Thanks

Hello!
Something like this, I hope it helps!

` <div>
            <Whatever />
        </div>`

**Comment by gwmccull** [comment]
this took me a while to figure out so I'll add my solution to help other people. In short, in your story, you need to wrap the component that creates the portal with a div with a height. Otherwise, it seems like Chromatic doesn't know the size of the snapshot it needs to take, so the portal is cut off

In my case, I was making a dropdown menu component that uses a portal. You can see my solution in the `Template`

```typescript
const Template: Story<MenuDropdownProps> = (args) => (
  <div style={{ width: 200, height: 400 }}>
    <MenuDropdown {...args} />
  </div>
);
const baseArgs: Partial<MenuDropdownProps> = {
  trigger: <Text>Menu</Text>,
  children: (
    <>
      <Text>child 1</Text>
      <Text>child 2</Text>
      <Text>child 3</Text>
    </>
  ),
  initialIsOpen: true,
};

export const Default = Template.bind({});
Default.args = {
  ...baseArgs,
};
Default.storyName = "Menu Dropdown";

```
