### ISSUE TITLE
No environment variables in chromatic github action

### ISSUE THREAD

**Issue by saiichihashimoto** [chromaui/chromatic-cli#272]
Using the github action, I want to [disable stories on a global level in `.storybook/preview.js`](https://www.chromatic.com/docs/ignoring-elements#ignore-stories) with an environment variable. It doesn't work and, when I render a story with `<pre>{JSON.stringify(process.env, null, 4)}</pre>`, all I get is:

```json
{
    "NODE_ENV": "production",
    "NODE_PATH": "",
    "STORYBOOK": "true",
    "PUBLIC_URL": "."
}
```

This must be filtering out environment variables somehow, considering that there is a [large list of environment variables](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables) that are available in github actions.

Is there a way to not filter these out? Or at least allow me to define some environment variables I want to allow through?

**Comment by saiichihashimoto** [comment]
Are there more details I should be adding? I'm not sure how to push this forward.

**Comment by phil-r** [comment]
I think it's not a chromatic issue, but storybook's. Storybook only works with [env variables that start with `STORYBOOK_`](https://storybook.js.org/docs/react/configure/environment-variables)

Here is what worked for us, The part of our workflow file(we use secret, not a github action env variable, you'll need to figure out how to rename it):

```
   - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          exitOnceUploaded: true
        env:
          STORYBOOK_API_URL: ${{ secrets.API_URL }}
```

and in code we can now access `process.env.STORYBOOK_API_URL`.

IMHO this should be better documented on chromatic's side.

**Comment by tmeasday** [comment]
@saiichihashimoto did this solve your problem?

**Comment by tmeasday** [comment]
@phil-r -- can I ask where you would have expected to find that documentation? cc @jonniebigodes

**Comment by phil-r** [comment]
Maybe here https://www.chromatic.com/docs/github-actions or just have a separate page with a tldr that Chromatic is based on storybook and follows the same env variable naming scheme with a link to https://storybook.js.org/docs/react/configure/environment-variables ?

**Comment by tmeasday** [comment]
Thanks @phil-r! @jonniebigodes can we track this somewhere? Thanks!

**Comment by jonniebigodes** [comment]
@tmeasday on it. Going to add this to my task list. @phil-r thanks for bringing this to our attention. 

Stay safe

**Comment by saiichihashimoto** [comment]
Sorry for the delayed response @tmeasday. This identified the issue, but I'd really like env vars to be treated normally in storybook. Any code that uses env vars now has to use both the normal env var and the STORYBOOK_ version arbitrarily. If other frameworks required this, any usage of an env var would need a long chain of these. `process.env.STORYBOOK_VAR ?? process.env.SOMEONE_ELSE_WHO_DOES_THIS_VAR ?? ... ?? process.env.VAR`

**Comment by tmeasday** [comment]
@saiichihashimoto the reason they aren't is it is a security concern. The env vars are built into the the SB artifact which is uploaded to the internet. If it swept up the whole CI environment there'd be more than a good chance there'd be a bunch of private keys in there.

**Comment by brett-east** [comment]
Is there not a way that you can allow environment variables that come from `${{ secrets.VAR_NAME }}`, like @saiichihashimoto says, trying to chain these environment variables in the code doesn't make sense at all.

My app shouldn't need to know anything at all about storybook, and I don't want any storybook specific 
code in a component or page.

I would love to be able to specifically and intentionally pass in environment variables into my chromatic.yml
file like so:

```
        env:
          #👇 Sets the environment variable
          SOME_VAR: 'a random string'
          SOME_OTHER_VAR: ${{ secrets.SOME_OTHER_VAR }}
```

I'm getting storybook errors because I can't start some parts of the app that require keys, and it doesn't
seem to make any sense to me at all to need to include `STORYBOOK_` and check for it anywhere in my
code.

For what it's worth, storybook deploys completely fine from the cli, because it is running though my
webpack in the main.ts, but for some reason this isn't working with the github action.

How can I get an environment variable that isn't prefixed with `STORYBOOK_` into my storybook build,
or how can I get the github action to behave like the chromatic cli where I can make the builds work.

Or at the very least what is the expected pattern? Writing something like `STORYBOOK_PAYPAL_INIT_KEY`,
and then using in my codebase, just so that storybook can also use it feels a lot like smelly code.

Am I missing something? Like why does the cli work and the github action doesn't, when adding my environment
variables?

**Comment by tmeasday** [comment]
@brett-east - I'm a little bit confused here, it seems you are talking about two issues at the same time, so can I unpack a bit:

**1. Storybook doesn't pull arbitrary env variables into a build.** This is a security consideration [as discussed above](https://github.com/chromaui/chromatic-cli/issues/272#issuecomment-817261706). 

There is a workaround, which is to use an `.env` file. Storybook will read that. However, I think we consider this a bit of a security risk as well and might remove it in a future version, which is why it isn't documented.

> Or at the very least what is the expected pattern? Writing something like STORYBOOK_PAYPAL_INIT_KEY,
and then using in my codebase, just so that storybook can also use it feels a lot like smelly code.

My recommendation would be not to read `process.env` directly in your components (that seems smelly too IMO). If they need that info, put it in a context provider, and create a special provider in a project-level decorator in Storybook:

```js
// preview.js
export decorators = [(S) => <EnvProvider env={{ setting: 'value' }}><S/></Env>
```

I would also suggest you wouldn't be reading those values from the environment anyway. You want your SB to be consistent no matter where it is build, I think.

**2. The Chromatic action isn't passing the same env vars as the CLI**: is this the case? That sounds like a bug but doesn't seem to be what folks were reporting originally on this issue.

**Comment by tmeasday** [comment]
Oh, @shilman mentioned another (better) way you can set arbitrary env in your SB: `main.js` has an `env` field and you can put what you like in there, including reading `process.env`. I would suggest that as the simplest option right now:

```js
// main.js

export {
  env: {
     SOMETHING: process.env.SOMETHING,
  }
}
```

**Comment by tmeasday** [comment]
@jonniebigodes we should document the above alongside https://storybook.js.org/docs/react/configure/environment-variables?

**Comment by jonniebigodes** [comment]
Thanks for putting this on my radar @tmeasday, I'll update the task and factor in the change into Storybook's docs.

**Comment by saiichihashimoto** [comment]
Ran into this same problem after debugging for a few hours with another developer. This isn't very intuitive, nor does it separate concerns very well. Is there not a way to tree-shake env vars that aren't used in the storybook as a way to handle the security concern? Prefixed env vars seems worse than the problem its solving (env vars out of sync, hard to debug issues, etc) or requiring a [specific pattern of reading env variables](https://github.com/chromaui/chromatic-cli/issues/272#issuecomment-1059463069) like @tmeasday suggested means storybook has very specific opinions about how you should involve config, which doesn't seem like something it shouldn't enforce/restrict.

Either way, my solution to never think about this again:

```js
module.exports = {
  env: (config) => ({
    ...config,
    ...process.env,
  }),
};
```
