### ISSUE TITLE
Add isolatorURL to action outputs

### ISSUE THREAD

**Issue by ndelangen** [chromaui/chromatic-cli#277]
The output could be added, the isolatorURL (where the iframe.html is hosted) is saved on the 'context' here:https://github.com/chromaui/chromatic-cli/blob/c6964c91ee42a5020e8ce6633cbccd6e773428c2/bin/tasks/start.js#L22

The resulting context can be extracted here:https://github.com/chromaui/chromatic-cli/blob/c6964c91ee42a5020e8ce6633cbccd6e773428c2/action/main.ts#L86

Then set as an output for the action here:https://github.com/chromaui/chromatic-cli/blob/c6964c91ee42a5020e8ce6633cbccd6e773428c2/action/main.ts#L147-L149

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1199953298564783) by [Unito](https://www.unito.io/learn-more)

**Comment by deebov** [comment]
may I know why this issue was closed? Because the `storybookUrl` that's exposed to the output is wrong (empty).

This should be `ctx.isolatorUrl` instead of `ctx.build.isolatorUrl`:

https://github.com/chromaui/chromatic-cli/blob/0c4ed314d7ea31bb8e1953f316653e5bfb4bdfeb/action/main.ts#L84

Where (I suppose) the actual link to `isolatorUrl` is set:

https://github.com/chromaui/chromatic-cli/blob/0c4ed314d7ea31bb8e1953f316653e5bfb4bdfeb/bin/tasks/upload.js#L124

**Comment by ghengeveld** [comment]
This should be `ctx.build?.cachedUrl`

**Comment by ndelangen** [comment]
ow! no!

**Comment by ndelangen** [comment]
should be an easy fix then right @ghengeveld ?

**Comment by ghengeveld** [comment]
Yes, just use `cachedUrl`. `isolatorUrl` isn't something that should be used after the build is done.

**Comment by deebov** [comment]
Thanks for reopening this. 

Should I make a PR?

**Comment by ndelangen** [comment]
I'll do it today!

**Comment by ndelangen** [comment]
@ghengeveld I think that was released now?
