### ISSUE TITLE
Sorry, but you either have no stories or none are selected somehow.

### ISSUE THREAD

**Issue by juliangsibecas** [chromaui/chromatic-cli#312]
Hey! How it's going? Chromatic is not showing the stories content. I've tested in Brave and Mozilla. My local storybook build is working as expected.

![image](https://user-images.githubusercontent.com/25715495/111888043-d9bd1480-89b7-11eb-9d68-fe1736dbaec0.png)

Test.stories.tsx:
```
import { Meta } from '@storybook/react'

export const Test = () => <p>hello!</p>

export default {
  title: 'Components/Test'
} as Meta
```

main.js:
```
import React from "react";
import { ThemeProvider } from "styled-components";
import { addDecorator } from "@storybook/react";
import { GlobalStyle } from "../src/globalStyles";
import { defaultTheme } from "../src/theme/default";
import { withThemesProvider } from "storybook-addon-styled-component-theme";

const themes = [defaultTheme];

addDecorator(withThemesProvider(themes), ThemeProvider);

export const decorators = [
  (Story) => (
    <>
      <GlobalStyle />
      <Story />
    </>
  ),
];

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
};
```
preview.js:
```
import React from "react";
import { ThemeProvider } from "styled-components";
import { addDecorator } from "@storybook/react";
import { GlobalStyle } from "../src/globalStyles";
import { defaultTheme } from "../src/theme/default";
import { withThemesProvider } from "storybook-addon-styled-component-theme";

const themes = [defaultTheme];

addDecorator(withThemesProvider(themes), ThemeProvider);

export const decorators = [
  (Story) => (
    <>
      <GlobalStyle />
      <Story />
    </>
  ),
];

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
};
```

**Comment by tmeasday** [comment]
Hi @juliangsibecas -- it doesn't look like SB is showing that `sb-nopreview` element (it is always in the DOM, just conditionally displayed based on a body class).

What is rendered in the `#root` element? Is there an error in the browser console?

**Comment by HosseinAgha** [comment]
I'm facing the same issue with `chromatic@5.8.0`, `@storybook/react@6.1.21`, and `npm@6.14.12`.  
Also looks like chromatic sends output options to `build-storybook` script in the wrong format (at least for npm 6 and before we should add a `--` for sending script specific params).  
![Screen Shot 2021-05-04 at 5 32 41 pm](https://user-images.githubusercontent.com/12998499/117007535-070f1900-acff-11eb-922b-54a1dd03287b.png)

**Comment by tmeasday** [comment]
> I had to provide a custom output option to both storybook and chromatic script in order for this to work. 

What did you mean by this?

> But I still see empty snapshots and canvas in the chromatic app. Although clicking on the view storybook button in the Library shows that stories are fine.

My guess is there is an error in the console when the story is rendered in Chromatic's Canvas view. Can you take a look?

**Comment by HosseinAgha** [comment]
> What did you mean by this?  

chromatic script: `chromatic --project-token=XXXXX -o storybook-build`  
build-storybook script: `build-storybook -c .storybook -s ./public -o storybook-build`

As in the current version, the chromatic script would never send the `--output-dir` args to `build-storybook` script, I had to provide the output directory to both scripts. Otherwise the output dir for build-storybook will be `storbook-static` (default output) and the output dir for chromatic will be somewhere in the `/tmp` and it cannot find the storybook built assets.

I don't get any errors in the console in the `DOM Diff` nor in the stories canvas, snapshot, etc pages.  
Only empty white pages everywhere.  
Although I get some Duplicate Title warnings in some scenarios. I had these warnings in storybook and everything was fine there.
The strange thing is that when I click the `View Storybook` button everything is fine.

**Comment by tmeasday** [comment]
Hi @HosseinAgha as far as I can tell Chromatic is passing the options to npm correctly. Is something unusual about your setup? It might be worth opening a separate issue about this.

> I don't get any errors in the console in the DOM Diff nor in the stories canvas, snapshot, etc pages.

Can you open a ticket with support and link to the stories in question on Chromatic please?

**Comment by HosseinAgha** [comment]
About sending arguments to npm scripts please chek out https://stackoverflow.com/questions/11580961/sending-command-line-arguments-to-npm-script  

Sure I'll try to open a ticket.

**Comment by josectobar** [comment]
I also have this same issue. I'm running an ejected `create-react-app` using `chromatic@5.9.2`, `storybook/react@6.2.8`and `npm@6.14.11`. I noticed that although the components are blank in `chromatic` I'm able to see them if I click the `view Storybook` button. 
![image](https://user-images.githubusercontent.com/21246524/123867492-48790a80-d8e3-11eb-98f2-0acc8d879999.png)

**Comment by josectobar** [comment]
John from `Chromatic` pointed out the issue was coming from `storybook-addon-styled-component-theme` since it takes control over the rendering at runtime and it only seems to work in the Storybook UI context and not Chromatic's. I was able to fix the issue by using https://github.com/semoal/themeprovider-storybook instead. 🎉
