### ISSUE TITLE
Add a bail-out flag to only changed

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#340]
We need a way to flag to --only-change a glob of files that should trigger a bailout, something like `--skip-only-changed-for="**/*.mjml"`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200357127387902) by [Unito](https://www.unito.io)

**Comment by zol** [comment]
Yeah this is important to add and document before we ship this feature to everyone because I know from talking to people firsthand that there are all sorts of quirky build time hacks floating around out there.

I'd like to think of a better name though, `skip-only-changed` has a confusing double negative in it. 

@gert or @tmeasday what does the `[branch]` parameter to `--only-changed` do exactly and could that be used separately to `--only-changed`?

**Comment by tmeasday** [comment]
We are thinking we will call this `--externals`

**Comment by zol** [comment]
By 'this' do you mean instead of `--skip-only-changed`? What is the `[branch]` parameter for? I'm wondering whether this could be broken out as an independent parameter and then the argument to `--only-changed` could be externals list.

**Comment by ghengeveld** [comment]
Implemented here: https://github.com/chromaui/chromatic-cli/pull/355

**Comment by tmeasday** [comment]
The `branch` parameter is for saying "only do `--only-changed` if we are on this branch`. It is a standard pattern we have in the CLI, for instance for `--auto-accept-changes=master`.

> I'm wondering whether this could be broken out as an independent parameter and then the argument to --only-changed could be the externals list

To me that would be confusing though. If I read `--only-changed=*.sass` I would read that to mean "only run chromatic when sass files have changed", which isn't quite what we mean. We mean "only run *every chromatic test* when sass files have changed".

**Comment by zol** [comment]
Sgtm, let's go with `--externals`

**Comment by tmeasday** [comment]
Heh, already done: https://github.com/chromaui/chromatic-cli/pull/355
