### ISSUE TITLE
Allow specifying location of dotenv file

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#352]
NextJS uses non-standard `.env.local` etc. Can we make a CLI flag to let users specify this location?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200545741323003) by [Unito](https://www.unito.io)

**Comment by bodograumann** [comment]
Yes, please, for us vue-cli users.

**Comment by matthew-serretta** [comment]
this would also be useful for use in a monorepo where chromatic is only used in 1 repo. Instead of needing to create a project .env file (e.g. `monorepo/project/.env`) you could specify the root .env (`monorepo/.env`).

Atm I'm using `--project-token=$(grep CHROMATIC_PROJECT_TOKEN ../../.env | cut -d '=' -f2)` to get around this.

**Comment by dobesv** [comment]
I think you can do something like `DOTENV_CONFIG_PATH=$PROJECT_CWD/.env chromatic`

However, now that they recommend using a different token for each project in the monorepo this doesn't quite do the job since you would want to pull out the appropriate token for your specific project.

**Comment by dobesv** [comment]
See also https://github.com/chromaui/chromatic-cli/issues/717

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
