### ISSUE TITLE
async.finally() is not a function

### ISSUE THREAD

**Issue by ckim16** [chromaui/chromatic-cli#371]
chromatic version: ^5.8.0
node version: 12.19.0

I have___ a `.finally` followed by an asynchronous function in one of my components and that breaks in chromatic build.
```
{
  "stack": "<stack trace above>",
  "message": "Error: AsyncFunction(...).finally is not a function"
}
```
does anybody know the solution for this?

**Comment by ghengeveld** [comment]
Hi @ckim16 can you maybe share the code where you're using `.finally`? It's supported in Chrome and Firefox, as well as Node.js, so it seems either you're testing against IE, or there's something weird about your code.

Typically the best way to [reach out](https://www.chromatic.com/docs/support) with this sort of issue is through Intercom (chat) in Chromatic.

**Comment by ckim16** [comment]
@ghengeveld thanks for the feedback! since it's the company work, can't really share the details of the code. but we're not testing against IE and the component is displaying on the Storybook. wondering that there is any configuration that I'm missing for the Chromatic set up but will reach out to Chromatic team and see if they can fix this issue.
Thanks!

**Comment by ckim16** [comment]
just fyi, `.finally` is followed by the asynchronous function straight without `.then` or `.catch`. for now, that would be my best guess why this is not working but will keep investigating this.

**Comment by tmeasday** [comment]
I believe this was covered in Chromatic Support and the issue is the old version of Firefox we are on not having proper support for `.finally()`. We are in the process of upgrading our FF version to a much more recent version that will support this. Apologies in the meantime! You could look at adding a polyfill for this in the short term.

Let me know if I have that wrong.
