### ISSUE TITLE
Look at more than the current commit for squash merges

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#375]
The current algorithm for squash merge detection considers the commit being tested and checks if it is the "merge commit" of a PR. If it is, it adds the head commit of the PR as a baseline commit, in case the PR was squash or rebase-merged.

```
A - - - M
  \        
    B - C [PR #N, merged as M]
```

This works if the build runs for `M` before any of `M`'s children (as the children of `M` will get `M`'s baselines carried over).

However in certain race conditions it is possible for a child of `M` to run before `M`:

```
A - - - M - D
  \        
    B - C [PR #N, merged as M]
```

Now, when `D` runs (assuming `M` has not run yet), we will:
  a) look for a merged PR with merge commit `D` ❌ 
  b) look for a build on `M` ❌ 
  c) take baselines from `A`.

Then we lose the baselines in `C`.

To resolve this, we should check all commits between `D` and the baseline commit (`A`) to see if they are merge commits for PRs. Probably we can only do that for a small number of commits (as each check involves an upstream query to the provider), but chances are even a small number of extra checks will be sufficient.

**Comment by nigel-codaio** [comment]
This would be super helpful for us -- currently, we ensure all running chromatic builds on our `main` branch are queued and drained in commit order.  This adds more latency to our builds/pipeline and the proposed solution here would make things such simpler.

**Comment by wlechowicz** [comment]
+1 on this, I have squash as the default strategy and when PR owner merges in develop branch into the feature branch for his PR (so a merge commit is created on his feature branch), Chromatic looks only at the merge commit and assumes there's no baseline and shows all the new stories pulled in from develop as brand new in that PR despite them being already present and approved on develop.

Issue is, the commit right before merge (so the HEAD of develop branch) has a green build and should be the new baseline for this PR that merged develop in. But Chromatic seemingly doesn't look past the merge commit. Potential solution? Rebase PR branch each time instead of merging develop in, but docs say it should work:
> To work around this, merging (or rebasing) the base branch into the feature branch will resolve the issue, as demonstrated above.

but it doesn't. In terms of OP, my D (new PR) keeps looking at A's build as a baseline because it doesn't see M.

**Comment by tmeasday** [comment]
@wlechowicz can you write into Chromatic support with some links to examples of the above happening? Are you running Chromatic on the squash merge commits?

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.

**Comment by tmeasday** [comment]
We also ended up implementing this too.
