### ISSUE TITLE
Snapshot Different With v5 Centered Addon and v6 Layout: Centered

### ISSUE THREAD

**Issue by pxwee5** [chromaui/chromatic-cli#390]
This is a Chromatic snapshot diff of the triple dot component.
![image](https://user-images.githubusercontent.com/14123790/130374522-3fe42835-c101-4fa8-8ef8-ca437f3c47f0.png)

Left: Chromatic snapshot rendered with `@storybook/addon-centered` addon used with Storybook v5.
Right: Chromatic snapshot rendered with `layout: 'centered'` config in Storybook v6's.

The upgrade trigged errors in all of the components in Chromatic. 

Question is which is the correct?

PS: Move this to the correct repository if this is not the right place to raise this issue.

**Comment by ghengeveld** [comment]
Hi @pxwee5 

We'll have to take a closer look at your component to determine why it's considered visually different. Please use our [support chat](https://www.chromatic.com/docs/support) (the blue button in the bottom-right corner) or send us an email at `support@chromatic.com`.

Closing because this is not an issue with the CLI.
