### ISSUE TITLE
Chromatic Demo flow fails to work with the CLI

### ISSUE THREAD

**Issue by dudulasry** [chromaui/chromatic-cli#398]
Hey everyone,

I just installed chromatic in my project and started the tutorial of Chromatic. However, when I get to the point where I need to make some change in the UI and publish again, the CLI fails to do that.

This is the error I got:
```
✖ Found 1 visual change: failing with exit code 1
Pass --exit-zero-on-changes to succeed this command regardless of changes.
Pass --auto-accept-changes to succeed and automatically accept any changes.
ℹ Review the changes at https://www.chromatic.com/build?appId=613a7735df6708003ac5c227&number=6
```

I added the flag `--exit-zero-on-changes` in order to continue the tutorial. I think the tutorial should be updated

**Comment by domyen** [comment]
@dudulasry thanks for reporting this. I'm looking into it. Do you mind linking me to the tutorial you referenced (for example, on the Chromatic website, Storybook site, or elsewhere)?

**Comment by dudulasry** [comment]
@domyen It's the first tutorial someone sees when creating a new project in Chromatic. I'm not sure how to link to it 🧐

**Comment by domyen** [comment]
Hey Dudu, I just ran through the onboarding myself. The message you're seeing is intentional and you completed the workflow successfully.

> ✖ Found 18 visual changes: failing with exit code 1
Pass --exit-zero-on-changes to succeed this command regardless of changes.
Pass --auto-accept-changes to succeed and automatically accept any changes.

"Failing with exit-code 1" message is for folks that are setting up CI. I can see how it'd be confusing at this stage in the process. Will chat with the team here about tweaking this messaging.

![image](https://user-images.githubusercontent.com/263385/133634478-c9142936-1c13-4f4b-a2eb-2e3e02b4b721.png)
