### ISSUE TITLE
Support `staticDirs` in Storybook config

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/chromatic-cli#462]
In Storybook 6.4, the `--static-dir` or `-s` flag is [deprecated](https://storybook.js.org/docs/react/configure/images-and-assets#%EF%B8%8F-deprecated-serving-static-files-via-storybook-cli) in favor of the `staticDirs` configuration in `.storybook/main.js`.

The Chromatic CLI currently [pulls the `staticDir`](https://github.com/chromaui/chromatic-cli/blob/3e4c4d3d8b59fd5db61df96b800d610cb0b03b72/bin-src/lib/getStorybookInfo.js#L120) from the build script, but does not support the `staticDirs` configuration option.

This option is used to [determine](https://github.com/chromaui/chromatic-cli/blob/3e4c4d3d8b59fd5db61df96b800d610cb0b03b72/bin-src/lib/getDependentStoryFiles.js#L102) which files should cause TurboSnap to bail.

Blocked by https://github.com/storybookjs/storybook/issues/16990

**Comment by AdamVig** [comment]
[The workaround for this](https://www.chromatic.com/docs/turbosnap/#specify-external-files-to-trigger-a-full-re-test-when-they-change) is easy enough, but it looks like [the linked blocker issue](https://github.com/storybookjs/storybook/issues/16990) is resolved–could this now be implemented so that the Chromatic CLI automatically picks up this configuration option?

**Comment by tmeasday** [comment]
@shilman is there any way to get the `staticDirs` option from `main.js` (after a build)? I don't think it's in `project.json`, right?

**Comment by shilman** [comment]
@tmeasday Not AFAIK

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
