### ISSUE TITLE
[Request] Show CSS in Story Inspector

### ISSUE THREAD

**Issue by victor-grajski** [chromaui/chromatic-cli#497]
I'm wondering if there's been any internal discussion about showing CSS in the story inspector. Much like the DOM diff feature helps me verify the markup, my designer and I would like to be able to review CSS values like background-color before approving without having to inspect the story in Storybook using dev tools. Thank you!

<img width="1792" alt="Screen Shot 2022-01-11 at 2 25 51 PM" src="https://user-images.githubusercontent.com/3674075/149031220-68dc3485-0f00-4bfe-9fc4-c0a75d2f2781.png">

**Comment by winkerVSbecks** [comment]
Hey Victor,

The Styles can be defined in various location so, realistically we'll have to find the actual CSSOM for every DOM node within the snapshot. We've explored it in the past but, haven't found a great solution yet. That said, I'll pass this on as a feature request to the team since this would be handled on the Chromatic webapp side and not the CLI.

**Comment by wshager** [comment]
@winkerVSbecks Where's the feature request?
