### ISSUE TITLE
Chromatic can not see the difference with main branch

### ISSUE THREAD

**Issue by muratcorlu** [chromaui/chromatic-cli#608]
We are using Chromatic to run visual regression tests for our new [UI library](https://github.com/Trendyol/baklava). But [in a PR](https://github.com/Trendyol/baklava/pull/159) somehow it doesn't see the difference (a new component is introduced here) with main branch and doesn't build and publish Storybook at all. Here is the action log: https://github.com/Trendyol/baklava/runs/7428619091?check_suite_focus=true

It says: `No visual changes were found in this build.`

Currently we manually run chromatic from our local with `--force-rebuild` parameter to bypass this after every commit to the PR.

I think there is a detail that we miss about how chromatic understands the difference. Can someone help about this issue?

**Comment by tmeasday** [comment]
Hi @muratcorlu the issue here is the stories that were added aren't in the storybook:https://6267ebb4dd54f5004a65f14a-ozustswifa.chromatic.com/?path=/story/documentation-welcome--page


It looks like you sorted that out in later builds? I see changes on the PR now: https://www.chromatic.com/build?appId=6267ebb4dd54f5004a65f14a&number=154

**Comment by muratcorlu** [comment]
Hi @tmeasday. We needed to manually push a build with `--force-rebuild`. But somehow when we push our changes to the branch `chromaui/action` runs a build with the version of main branch, not current branch. And then continuous pushes to the same branch even doesn't trigger a build since chromaui/action says `Skipping rebuild of an already fully passed/accepted build` Look: https://github.com/Trendyol/baklava/runs/7426008539?check_suite_focus=true But we didn't accepted any change for this PR.

**Comment by tmeasday** [comment]
Hi @muratcorlu -- I'm not quite sure. I'm looking at that log you posted, and I see:

<img width="395" alt="image" src="https://user-images.githubusercontent.com/132554/180672425-b651672f-2c1d-4b5e-b4cd-c81800f03b9c.png">

And there is a build in Chromatic with that commit:

https://www.chromatic.com/build?appId=6267ebb4dd54f5004a65f14a&number=143

So (I guess?) Chromatic is working as intended here. Perhaps the issue is somehow your actions setup is checking out the wrong commit?

**Comment by muratcorlu** [comment]
I think, I need some further investigation about the git history in that branch. I’ll share the result.

**Comment by muratcorlu** [comment]
I figured out the issue. We we using [`pull_request_target` event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) to trigger our PR pipelines. This event is using base branch as the source for pipeline. So nothing wrong with chromatic action here. Sorry for the misunderstanding. Closing the issue.
