### ISSUE TITLE
[Question] When to take a snapshot? 

### ISSUE THREAD

**Issue by swallowtail62** [chromaui/chromatic-cli#610]
I want to take a snapshot of the loading state of network(REST API)-dependent components.
If use `msw-storybook-addon` and wait a few seconds for the resource to be returned in mock API, end up with a snapshot drawn with the resource waiting for a response.

```ts
// SomeComponent.stories.tsx
export const Loading = () => {
  return <SomeComponent />
};
Loading.parameters = {
  msw: {
    handlers: [rest.get(`/resource`, async (req, res, ctx) => {
      await new Promise<void>((resolve) => {
        setTimeout(() => resolve(), 5_000);
      });
      return res(ctx.json({}); // resource
    }]
  }
}
```

Is it possible to take a snapshot of the loading state without waiting for a response?

https://www.chromatic.com/docs/snapshots

> For every story in your Storybook: Chromatic will load the story, wait for it to render, take a screenshot and crop it to the correct bounding region. Snapshots are stored in the cloud and used to determine UI changes between builds or branches.

How do you wait for a component to render?

**Comment by tmeasday** [comment]
Hey @swallowtail62, Chromatic endeavours to wait for network requests so my guess is it's going to be difficult to do this as you are sort of wanting it to do the exact opposite!

My suggestion here would be to refactor the component into a connected and presentational version, then write the "loading" story against the presentational version. That's going to be a better solution inside storybook also (otherwise the story's going to change after 5s which is pretty annoying I would have thought).

**Comment by swallowtail62** [comment]
@tmeasday 
OK, I'll split the components. Thanks!
