### ISSUE TITLE
Not wait for chromatic cloud todo its thing

### ISSUE THREAD

**Issue by benjaminkay93** [chromaui/chromatic-cli#62]
We currently use chromatic to build our storybook, upload it, and then wait for the build to complete like so.

`chromatic test --no-interactive --build-script-name=build`

We recently added `--exit-zero-on-changes` when we relised that the hook from chromatic back into our PR's would fail if stories had changed and then pass once we updated the story to be accepted. Thus meaning we always wanted to pass the CI step to avoi dhaving to run our Jenkins job in its entirety again.

This means the chromatic CLI now runs its build, uploads and waits for the success/failure to come back, essentially blocking our pipeline for 1.5 mins whilst chromatic does its stuff.

Is there anyway to just fire and forget the stories in our CI, so that when we run the chromatic CLI tool we just run the build and upload and not wait for a successful/failure of our stories inside chromatic itself? saving 1.5 mins of time because we have the chromatic hook to let us know if theres any failures?

**Comment by tmeasday** [comment]
Hi @benjaminkay93 that sounds like a reasonable request. We've considered it before and it's certainly sensible.

Would you be interested in implementing it yourself? It would probably be a matter of creating the option in the `bin/register.js` file and passing it through to the `tester/index.js` file and exiting sometime after making this API call: https://github.com/chromaui/chromatic-cli/blob/master/bin/tester/index.js#L356-L390

Let me know if so. Otherwise we'll try and get it prioritized soon.
