### ISSUE TITLE
chromatic build has diff on every PR regardless if it's previously been approved

### ISSUE THREAD

**Issue by saylestyler** [chromaui/chromatic-cli#627]
We have a custom component that has a story associated with it. The component has a dynamic width that uses `getBoundingClientRect()` in order to determine the dimensions, like so: 

```js
const { width } = active.getBoundingClientRect()
slider.style.width = `${width}px`
```

When the component was first added, or some time in the past, the width was determined to be different from what it is now. This means that for any PR, this component shows as having a diff and has to be re-approved. But regardless of whether or not it's approved, every time it reappears with the same exact width difference as if the original approval was not saved. 

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/20520284/184239012-0b808611-80bf-476e-acb4-240be8bd09c2.png">

**Comment by tmeasday** [comment]
Hi @saylestyler, it's probably best to write into Chromatic support so we can dig into the specifics of what you are doing.

Typically issues with baselines not being remembered are either due to the build (not having any ancestor)[https://www.chromatic.com/docs/branching-and-baselines#calculating-the-ancestor-builds] at all (you'll see a big warning on the build screen saying "No Ancestor Found") or baselines getting lost when you https://www.chromatic.com/docs/branching-and-baselines#squash-and-rebase-merging.
