### ISSUE TITLE
Dummy Project token when dry run ?

### ISSUE THREAD

**Issue by davidNHK** [chromaui/chromatic-cli#632]
**Feature request**

I want include chromatic in my project and keep it up to date with dependency bot

When package update is come, i want exec the `chromatic --dry-run` command to make sure it still working after update

I use `--dry-run` because i don't want really publish / update my live storybook. 

**Proposed solution**

don't verify `--project-token` when `--dry-run`

**Alternative solutions**

Any alternative solutions or workarounds you've considered.

**Additional context**

Contact customer support if you need to share private information you'd rather not disclose here.

**Comment by domyen** [comment]
Thanks for the the feature request @davidNHK 🙇 

In order to keep your project auto-updating with dependency bot, we _have_ to build Storybook and publish it in order to take snapshots which then update baselines for UI Test and UI Review. There's no other way.

If instead, you're looking for a "smoke test" to check that the component renders but doesn't update the image snapshots in Chromatic. I recommend looking into [DOM snapshot tests](https://storybook.js.org/docs/react/writing-tests/snapshot-testing) which render the component to check that it works. Not to be confused with Chromatic's _image_ snapshots. You'd run the snapshot tests as another step in the CI workflow **alongside** Chromatic.
