### ISSUE TITLE
Can chromaui only report result without take github ci time to run test ?

### ISSUE THREAD

**Issue by anhdd-kuro** [chromaui/chromatic-cli#638]
**Feature request**

I'm writing interaction test in storybook and automate it with chromaui
My project have many tests and sure it take time to run
It's hard to explain but with vercel , the deployment run on vercel itself and dose not take time for github CI and still report the result
Can chromatic do the same thing?
I means chromatic tests took time and gonna exceed CI time on my github plan soon
If there aren't a solution may be I will have to move all the test to jest and just use chromatic for visual snapshot test

**Proposed solution**

I don't know if it's even possible or not

**Comment by ghengeveld** [comment]
Sounds like you're running into the free plan limits for GitHub Actions. There's two things you can do to speed it up:
- Run Chromatic with `exitOnceUploaded: true` -- this will exit the CI script early, saving you some minutes
- Build your Storybook elsewhere, and use the `storybookBuildDir` option to provide the already-built Storybook to Chromatic

Where you build your Storybook is up to you. Chromatic does not provide a way to do that because we do not have access to your source code.

See also: https://www.chromatic.com/docs/github-actions#available-options
