### ISSUE TITLE
chromaui/action doesn't support merge_group events

### ISSUE THREAD

**Issue by janeklb** [chromaui/chromatic-cli#741]
**Bug report**

We would like to run the `chromaui/action` github action as part of our (new) [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) workflow. Unfortunately the chromaui action errors out saying it doesn't support the `merge_group` event

![image](https://user-images.githubusercontent.com/877396/233397737-9aa4f0ed-915e-4946-92f6-4b1e8e64ee7e.png)

_Not sure if this should be called a bug or a feature request - please feel free to triage it accordingly!_

**Comment by chinanderm** [comment]
We are running into this issue now as well. We have our Chromatic workflows as required checks on our PRs, thus those checks need to also run in the merge queue checks.

Any update on this from the Chromatic team?

**Comment by chinanderm** [comment]
Chromatic team -- is there any update on this? This is preventing us from leveraging merge queue because we have our Chromatic UI tests as required PR checks.

**Comment by mhemmings** [comment]
It's such a shame this isn't working. Our Chromatic project was the main reason for us using merge queues, but we're not able to because of this issue. Manual races to see who can merge `main` and deploy first is probably the stickiest bit of our dev process.

For reference, our approach was:
- To fail any merges in the queue if any unaccepted changes appear in Chromatic. It's hoped this never happens, but of course if it does (e.g. something new in `main` causes unexpected behaviour in `feature-branch`) we _definitely_ want to stop and not merge it without human interaction!! (fix or accept Chromatic changes)
- We hoped to use `exitZeroOnChanges` to achieve this, which I think is correct?

I can't see any reason the restrictions are put in place? Our next step is to look at using the Chromatic CLI directly to get around this. If we make any progress with that approach, I'll share in here.

If there's any other info I can provide or help with anything at all, please do reach out.

**Comment by thafryer** [comment]
Hi Folks! We have added support for the merge_group event in [v7.6.0](https://github.com/chromaui/chromatic-cli/blob/main/CHANGELOG.md#v760-tue-oct-31-2023)! Thanks, @mhemmings, for the contribution!

**Comment by mhemmings** [comment]
Hey @thafryer 

We've having trouble using this with required Github checks. The "UI Review" check hangs indefinitely, as its status never gets reported by Chromatic. The status of "UI Tests" gets reported by Chromatic successfully.

Ideally, our workflow is as documented above, where we want Chromatic to check there are "not accepted" changes within the queue (changes get accepted at PR time, and PRs can't be merged without them)

While on this topic, do you understand the difference between "UI Tests" and "UI Review", and why our designer needs to accept all changes twice and in different ways, to get these checks passing? It's all very confusing!!

Thanks in advance for your help!

<img width="810" alt="Screenshot 2023-11-01 at 13 32 24" src="https://github.com/chromaui/chromatic-cli/assets/5692567/72e92656-7571-4b68-b0a1-6528a4ab9e94">

**Comment by janeklb** [comment]
> While on this topic, do you understand the difference between "UI Tests" and "UI Review", and why our designer needs to accept all changes twice and in different ways, to get these checks passing? It's all very confusing!!

I'm still not 100% clear about the difference, but something that has helped my team is having engineers/developers take responsibility for "UI Tests" (they are incrementally updated each time you build a branch), and only involve the designer for "UI Review" (which is updated in full on every run)
