### ISSUE TITLE
Flag to disabled plopping build-storybook.log into my repo

### ISSUE THREAD

**Issue by dleavitt** [chromaui/chromatic-cli#831]
**Feature request**

Any time I run the chromatic CLI (or node app) it deposits a log file (`build-storybook.log`) into cwd. It does it even if nothing goes wrong, and I don't think I can stop it from doing so.

This doesn't seem like something a well-behaved command or library should do, and presumably causes problems in environments where cwd isn't writable (I have not tested this.) 

**Proposed solution**

A flag that stops chromatic from creating this file.

**Alternative solutions**

A flag that lets me send this output where it belongs, a gitignored log or tmp directory.

**Additional context**

Happy to back up my whining with a PR if you're open to this.

**Comment by work933k** [comment]
Same here.  "Chromatic.log" gets now added to our git-repository. Probably the log-file is unusable when running tasks in parallel (which we do with NX).

**Comment by work933k** [comment]
Any updates here?

**Comment by work933k** [comment]
Looking at the code.. It should be possible to prevent the creation of the chromatic.log file by setting the environment-variable "DISABLE_LOGGING". For me this should be a sufficient solution.

**Comment by dleavitt** [comment]
It looks like that works for `Chromatic.log`. `build-storybook.log` still gets generated for me.

**Comment by ghengeveld** [comment]
This was resolved in 9.1.0 with [this PR](https://github.com/chromaui/chromatic-cli/pull/855).

`build-storybook.log` has always been there, so that wasn't a regression. In fact we need `build-storybook.log` to be able to automatically fallback to the actual target directory if the temporary directory we provide isn't used (typically when the `build-storybook` script is doing something unusual). That's why we haven't disabled that log file by default (it would be a breaking change for some). Instead you can disable it explicitly via `storybookLogFile: false`. See also the [CLI config options](https://www.chromatic.com/docs/cli/#configuration-options).

**Comment by dleavitt** [comment]
thanks!
