### ISSUE TITLE
Turbosnap does not trigger full rebuild when storybook config changes

### ISSUE THREAD

**Issue by joshuajaco** [chromaui/chromatic-cli#862]
**Bug report**

According to the [docs](https://www.chromatic.com/docs/turbosnap/#full-rebuilds), changes to either `.storybook/main.ts` or `.storybook/preview.ts` should trigger a full rebuild.

However in our setup (pnpm monorepo + typescript + react) it does not trigger a rebuild.

I've created a [reproduction](https://github.com/joshuajaco/turbosnap-typescript-monorepo), with 3 PR's demonstrating the issue:

- [#3](https://github.com/joshuajaco/turbosnap-typescript-monorepo/pull/3) shows turbosnap working when changing a source file
- [#1](https://github.com/joshuajaco/turbosnap-typescript-monorepo/pull/1) shows turbosnap **NOT** working when changing `preview.ts`
- [#4](https://github.com/joshuajaco/turbosnap-typescript-monorepo/pull/4) shows turbosnap **NOT** working when changing `main.ts`

**Comment by bradleyayers** [comment]
I'm experiencing a similar thing, but in my case I have the following file structure:

```
.
├── .storybook
│   ├── main.ts
│   ├── preview-head.html
│   └── preview.ts
├── package.json
├── ...<snip>...
├── src
│   └── ...<snip>...
├── tsconfig.json
└── webpack.config.ts
```

Inside `.storybook/main.ts` is an `import { config } from "../webpack.config.ts";` line so that we can share parts of the webpack config between storybook and our normal build. The problem we had was that changes to `webpack.config.ts` weren't cache busting.

Looking at https://github.com/chromaui/chromatic-cli/blob/7ab18aa5a7512dfe51a9e5616a04aba8c8c3f006/node-src/tasks/gitInfo.ts#L196 I see where `package.json` can contribute to a rebuild, but I don't see how the storybook or webpack config contributes. Perhaps I'm looking in the wrong part of the code.

**Comment by paulelliott** [comment]
This should be fixed. Please reopen if you feel this is still relevant for you.
