### ISSUE TITLE
Specifying junitReport: true makes chromatic crash when reporting build status

### ISSUE THREAD

**Issue by woutervanvliet** [chromaui/chromatic-cli#935]
**Bug report**

I just enabled junitReport: true in my chromatic config file, mainly to explore what it can be used for. After that, every chromatic build started to fail with 

```
TypeError: ✖ Failed to generate build report
n.replace is not a function
at sbn (PATH\node_modules\chromatic\dist\chunk-EEJPR7JT.js:995:143)
at TW.task (PATH\node_modules\chromatic\dist\chunk-EEJPR7JT.js:638:24698)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Disabling junitReport works around the issue.

A solution to this ticket could be to check if junitReport is defined, and report a warning or error if it's not - instead of a runtime error.

I'm not using junit myself (yet?), so I don't be able to provide any further information.

**Comment by andrewortwein** [comment]
Thanks, I'm able to reproduce this using CLI v11.0.0. Is that the version you are using?

**Comment by andrewortwein** [comment]
@woutervanvliet to be specific, when the CLI command fails for me, it only fails _after_ tests complete and a build is produced that I can access on www.chromatic.com. Is that your experience as well?

For now, a workaround that I was able to use is to use the `--junit-report` CLI flag instead of specifying the option in the config file.

**Comment by woutervanvliet** [comment]
@andrewortwein That's exactly what I experience as well.

**Comment by andrewortwein** [comment]
@woutervanvliet this should be fixed now. Can you try it with the latest patch release?
